services:
    nginx:
        container_name: nginx
        build: requirements/nginx
        volumes:
            - wp:/var/www/html
        networks:
            - inception-network
        ports:
            - "443:443"
        depends_on:
            - wordpress
        restart: always

    wordpress:
        container_name: wordpress
        build: requirements/wordpress
        volumes:
            - wp:/var/www/html
        environment:
            DOMAIN_NAME: ${DOMAIN_NAME}
            WP_TITLE: ${WP_TITLE}
            WP_ADMIN: ${WP_ADMIN}
            WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
            WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
            WP_USER: ${WP_USER}
            WP_USER_PASSWORD: ${WP_USER_PASSWORD}
            WP_USER_EMAIL: ${WP_USER_EMAIL}
            DB_HOSTNAME: ${DB_HOSTNAME}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        networks:
            - inception-network
        depends_on:
            - mariadb
        restart: always

    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        volumes:
            - db:/var/lib/mysql
        environment:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        networks:
            - inception-network
        restart: always


volumes:
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/db
    wp:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/wp
networks:
    inception-network:
        driver: bridge